name: Auto Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]
  status:

permissions:
  contents: write
jobs:
  automerge:
    if: github.actor == 'exercism-solutions-syncer[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge PR
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GH_TOKEN}}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;

            await github.rest.pulls.merge({
              owner,
              repo,
              pull_number: prNumber,
              merge_method: 'squash', 
            });
            console.log(`Pull Request #${prNumber} merged successfully.`);
